### ISSUE TITLE
Allow re-use of app settings

### ISSUE THREAD

**Issue by GeertvanHorrik** [ohadschn/letsencrypt-webapp-renewer#1]
I find myself re-applying a lot of the same values to multiple sites in a resource groups. A lot could be shared (e.g. letsencrypt:default-subscriptionId, letsencrypt:default-tenantId, etc).

Then when I set up my resource groups correctly, I would only have to add different values for this:

letsencrypt:my-web-app-hosts: mywebhost.mydomain.com

**Comment by ohadschn** [comment]
I completely agree, and I indeed planned to add this feature.
Here are the possibilities I had in mind for shared settings, let me know what you think:
* Subscription ID
* Tenant ID
* Email
* Client ID
* Client Secret

**Comment by GeertvanHorrik** [comment]
That list seems complete!

Maybe you could even include resource-group. Some companies use a single resource-group (and it's default anyway, if letsencrypt:[website]-resource-group is specified it should use that anyway).

**Comment by ohadschn** [comment]
Yes of course the shared settings would always be overridable. Good call on the resource group.

**Comment by ohadschn** [comment]
Just released 0.8.5 released with this feature!

**Comment by GeertvanHorrik** [comment]
Great to hear, thank for all the efforts!
