### ISSUE TITLE
No ACME V2 support?

### ISSUE THREAD

**Issue by e-tara** [ohadschn/letsencrypt-webapp-renewer#102]
Due to upcoming the ACME 1 retirement, I upgraded to v1.0.5 and renewed some certificates successfully, however I have just received an email from LetsEncrypt stating...

"According to our records, the software client you're using to get Let's Encrypt TLS/SSL certificates issued or renewed at least one HTTPS certificate in the past two weeks using the ACMEv1 protocol. Here are the details of one recent ACMEv1 request from each of your account(s):

User agent:  ACMEdotNET v1.0.0.0 (ACME 1.0)

Request time:  2020-05-01 00:00:39 UTC"

Please can you confirm if I have to do anything to use ACME v2 e.g. update my configuration settings

**Comment by ohadschn** [comment]
Nothing to do from your end, only V2 is used since 1.0.4.

Just make sure you **only** have the new version installed (it's possible to have multiple web jobs installed, so you might have the old one still kicking).

**Comment by e-tara** [comment]
Apologies, I think this was a timing issue. I didn't realise but the "Request time" referred to in the email was 24 hours earlier than my recent successful executions and I can see in the web job logs that the more recent executions clearly refer to ACME v2.

LetsEncrypt appear to be sending these warning emails 18hrs after an attempt with ACME v1.

Great job on this app!
