### ISSUE TITLE
Cert error renewing

### ISSUE THREAD

**Issue by CodeBlanch** [ohadschn/letsencrypt-webapp-renewer#128]
From my WebJob log:

> [05/22/2024 20:13:55 > 9c2f7c: INFO] Error during Request or install certificate Certes.AcmeException: Can not find issuer 'C=US,O=Internet Security Research Group,CN=ISRG Root X1' for certificate 'C=US,O=Let's Encrypt,CN=R3'.
[05/22/2024 20:13:55 > 9c2f7c: INFO]    at Certes.Pkcs.CertificateStore.GetIssuers(Byte[] der)

Anything I can do about that?

**Comment by ohadschn** [comment]
@CodeBlanch see https://github.com/sjkp/letsencrypt-siteextension/issues/402#issuecomment-2079611564, it would probably require some code change and/or `Certes` package upgrade. 

I'm not maintaining this repo anymore, but if you want to submit a PR I wouldn't mind merging it so you get the CI build to install on your WebApp.

I'll ask the usual question though - why haven't you replaced this outdated WebJob with the free, officially supported built-in Microsoft option? https://learn.microsoft.com/en-us/azure/app-service/configure-ssl-certificate?tabs=apex#create-a-free-managed-certificate

**Comment by CodeBlanch** [comment]
> why haven't you replaced this outdated WebJob with the free, officially supported built-in Microsoft option?

Just laziness 🤣 I bit the bullet and went and updated all my sites, removed the webjob. Thanks for building this @ohadschn it was very useful for years.
