### ISSUE TITLE
Fails on Azure German Cloud

### ISSUE THREAD

**Issue by jessenic** [ohadschn/letsencrypt-webapp-renewer#13]
The WebJob is failing on Azure German Cloud. Is it trying to contact the general Azure portal instead of portal.microsoftazure.de?

`ERROR: Encountered exception: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS90038: Confidential Client is not supported in Cross Cloud request.`

**Comment by ohadschn** [comment]
Could you provide the full log?

**Comment by ohadschn** [comment]
Interesting, it looks like I need to add support for some more parameters:
https://github.com/sjkp/letsencrypt-siteextension/issues/64
https://github.com/sjkp/letsencrypt-siteextension/wiki/Azure-Germany,-US-or-China

I will try and get to it as soon as I can.

**Comment by berhir** [comment]
I had the same problem today. Do you have an update on the progress to support the German Azure Cloud?
Thanks!

**Comment by ohadschn** [comment]
@berhir I'm hoping to add it tomorrow, if not then probably next week. Of course I will accept a PR too :)

**Comment by ohadschn** [comment]
Just released [0.8.5](https://github.com/ohadschn/letsencrypt-webapp-renewer/releases/tag/0.8.5) with this feature.
