### ISSUE TITLE
Tries to renew every time it runs

### ISSUE THREAD

**Issue by dhilgarth** [ohadschn/letsencrypt-webapp-renewer#18]
I have the feeling that this app tries to renew all certificates every time it runs. It doesn't seem to respect the expiration times.
I have set it to run every day and I am being rate limited although I have only two certificates configured.
I plan on configuring it with a lot more certificates in the future. To avoid the rate limitation, it really should take into consideration the expiration of the certificate. The siteextension even has a setting for that: `letsencrypt:RenewXNumberOfDaysBeforeExpiration`

Or am I missing something?

**Comment by ohadschn** [comment]
You are correct, and looking at the code this should be a relatively simple fix.
I hope I will be able to make it this weekend.

**Comment by dhilgarth** [comment]
Awesome!


-------- Originalnachricht --------
Betreff: Re: [ohadschn/letsencrypt-webapp-renewer] Tries to renew every time it runs (#18)
Von: Ohad Schneider <notifications@github.com>
An: ohadschn/letsencrypt-webapp-renewer <letsencrypt-webapp-renewer@noreply.github.com>
Cc: Daniel Hilgarth <d.hilgarth@fire-development.com>,Author <author@noreply.github.com>


You are correct, and looking at the code this should be a relatively simple fix.
I hope I will be able to make it this weekend.

**Comment by dhilgarth** [comment]
Thanks! Will there be a new release soon?

**Comment by ohadschn** [comment]
Yes, the code is pretty much ready but I just want to run some tests.
I'm hoping for a release in the next few days...

**Comment by dhilgarth** [comment]
Great!

**Comment by ohadschn** [comment]
Released [0.8.5](https://github.com/ohadschn/letsencrypt-webapp-renewer/releases/tag/0.8.5) with this feature.
