### ISSUE TITLE
How to deploy to multiple slots with the same site name?

### ISSUE THREAD

**Issue by GeertvanHorrik** [ohadschn/letsencrypt-webapp-renewer#2]
First of all, thanks for this great extension, it's already working great in production. I couldn't find the free scheduled azure tasks, so I went for a free instance and will run it manually every 2 months.

All of my websites have a production and staging version. I have found the letsencrypt:webAppName-siteSlotName setting, but that only allows a single slot to be used for a site?

What I am trying to achieve:

1. mywebapp
2. mywebapp-staging:siteSlotName: staging

They are using the same sitename though and use *different* urls (e.g. myapp.mydomain.com and myapp-staging.mydomain.com).

I also tried creating multiple sites (e.g. postfixing all the settings for a site with *-staging*), but that didn't seem to work either.

Any ideas how this can be accomplished?

**Comment by ohadschn** [comment]
Thanks for the kind words @GeertvanHorrik!

First of all, the link I gave for setting up free WebJobs using Azure scheduler indeed wasn't detailed enough, but [that's fixed now](https://github.com/ohadschn/letsencrypt-webapp-renewer/blob/master/README.md#installation). It's kind of an annoying process but I guess you can't complain about the price...

Regarding multiple site slot names, let me know if I got this right. If we take the `hosts` configuration as an example, you'd want to be able to do something like this?

`webAppName-hosts`: `myapp.mydomain.com`
`webAppName{staging}-siteSlotName`: `staging`
`webAppName{staging}-hosts`: `myapp-staging.mydomain.com`

Where anything wrapped in `{}` would be ignored for the purposes of resolving the app name. In other words, the job will be executed multiple times with the same app name but different configurations?

If I understand correctly, that definitely makes sense. As a workaround until it's implemented, you could just create a dedicated cert-renewing web app per environment right?

**Comment by GeertvanHorrik** [comment]
1. Thanks for fixing the link.

2. Your understanding is correct. The workaround is a "lot" of work but I didn't consider creating a web app specifically for the staging sites. I would do letsencrypt-renewal and letsencrypt-renewal-staging to stay consistent. Thanks for the idea!

**Comment by ohadschn** [comment]
Glad I could help!
And thanks again for your suggestions. I should be able to implement them for the next release.

**Comment by ohadschn** [comment]
I gave it some thought and I don't think I'll implement this after all, I don't the value worth the added complexity.

I think creating another web app for staging purposes actually makes sense, especially when shared configuration settings are considered (for example, you might want self-signed certificates so you'll set a different ACME base URL in the staging site).

If anyone reading this disagrees, please comment here and let me know.

**Comment by dhilgarth** [comment]
So, are you considering to implement this?

**Comment by ohadschn** [comment]
Yeah, maybe I'll take a look in the weekend.
Perhaps I could replace the `siteSlotName` config with something like `webAppName{siteSlotName}-settingName`?

**Comment by dhilgarth** [comment]
You mean like you suggested three months ago? Yes, I think that would work.

**Comment by ohadschn** [comment]
Not _exactly_ as I suggested - I'm thinking the deployment slot name could be taken from the `{}`, thus removing the need for a dedicated `siteSlotName` setting.

**Comment by dhilgarth** [comment]
Sounds good!

**Comment by stuartleeks** [comment]
I've just hit exactly this issue - the change you proposed sounds good to me :-)

**Comment by ohadschn** [comment]
Message received :)

I didn't get to it last weekend but I will try to do it this one.

**Comment by ohadschn** [comment]
https://github.com/ohadschn/letsencrypt-webapp-renewer/releases/tag/0.8.5.1 released with this feature. I don't have any site with deployment slots so I couldn't test it, please let me know if it's working as expected.

**Comment by stuartleeks** [comment]
I've just tested it on one of my sites with a deployment slot and it looks like it worked fine here :-)

Thanks!
