### ISSUE TITLE
Do I need to uninstall "letsencrypt-siteextension" after installing letsencrypt-webapp-renewer?

### ISSUE THREAD

**Issue by wisdomware** [ohadschn/letsencrypt-webapp-renewer#37]
I was able to setup my SSL website with "letsencrypt-siteextension" and its WebJob is running continuously. My question is do I need to uninstall letsencrypt-siteextension WebJob after installing letsencrypt-webapp-renewer?

Thanks for creating this awesome tool!

**Comment by ohadschn** [comment]
The two are independent and unrelated, but I created this WebJob in order to remove the dependency on `letsencrypt-siteextension`. In theory you could keep both, but I don't see the point it and it might cause unnecessary multiple renewals and ensuing confusion.

**Comment by ohadschn** [comment]
Note that `letsencrypt-siteextension` lives on the **web app you want to renew** whereas `letsencrypt-webapp-renewer` typically lives on a dedicated renewal web app.

**Comment by wisdomware** [comment]
I got it. Thanks ohadschn!
