### ISSUE TITLE
Doesn't create a certificate for the first time

### ISSUE THREAD

**Issue by andrewgluh** [ohadschn/letsencrypt-webapp-renewer#39]
Web job will renew a certificate that already exists, but doesn't create a certificate for the first time like the letsencrypt extension.

This limits it's usefulness, especially for multi-tenanted apps where new domains are added on a regular basis.

**Comment by ohadschn** [comment]
The `letsencrypt-webapp-renewer` WebJob boils down to the same code as the site extension. It doesn't care whether a cert already exists or not (unless you specify `renewXNumberOfDaysBeforeExpiration` in which case it only checks its expiration date to see whether to run or not). When it runs, it simply creates a new cert and associates it with the appropriate Web App domains (regardless if there was a previous cert and/or association).

Indeed, I just created a blank new Web App with no cert configured, ran the `letsencrypt-webapp-renewer` WebJob and a new cert was configured successfully.

If this is not your experience, please share the exact steps you are taking and the full log of your WebJob run.

**Comment by ohadschn** [comment]
I see what's going on here, looks like the presence of `renewXNumberOfDaysBeforeExpiration` results in a different code path that indeed only renews. I'll see if I can work around that, I may need to ask Simon for another API in `LetsEncrypt.Azure.Core` (the library behind `letsencrypt-siteextension`).

**Comment by ohadschn** [comment]
Yeah, it looks like I need an API from the original site extension: https://github.com/sjkp/letsencrypt-siteextension/issues/188.

**Comment by andrewgluh** [comment]
Thanks for the update Ohad.
Looking forward to a resolution.

**Comment by ohadschn** [comment]
Fixed by https://github.com/ohadschn/letsencrypt-webapp-renewer/pull/76
