### ISSUE TITLE
Add support for wildcard certificates

### ISSUE THREAD

**Issue by casperOne** [ohadschn/letsencrypt-webapp-renewer#44]
It was announced that Let's Encrypt now supports wildcard certificates.

Support for wildcard certificates would be a great addition (although can currently be worked around, of course).

https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

**Comment by ohadschn** [comment]
We would have to wait for support from the underlying library: https://github.com/sjkp/letsencrypt-siteextension/issues/183.

Feel free to upvote that issue to catch Simon's attention...

**Comment by ohadschn** [comment]
@elucidsoft for what it's worth, I'm working on `letsencrypt-webapp-renewer` on my own free time as an open source developer too (my capacity as a Microsoft employee has nothing to do with this project).

**Comment by elucidsoft** [comment]
My point was, the uservoice request wanted official support. To list this as the resulution to that request is not want we wanted.

**Comment by rbanks54** [comment]
@ohadschn An updated nuget package for letsencrypt.azure.core has been posted (see https://github.com/sjkp/letsencrypt-siteextension/issues/183#issuecomment-455763588) 

It should hopefully unblock this issue.

**Comment by ohadschn** [comment]
@rbanks54 thank for letting me know, I'll take a look, don't think a PR will be necessary :)

**Comment by ohadschn** [comment]
So reading the info on the other thread, it looks like I'll need to use `LetsEncrypt.Azure.Core.CertificateManager.CreateAzureDnsWebAppCertificateManager` instead of `CreateKuduWebAppCertificateManager` (because the DNS challenge is necessary for wildcard certs).

**Comment by casperOne** [comment]
When this is complete, will we be able to issue non-wildcard challenges via DNS?

**Comment by ohadschn** [comment]
@casperOne sure, no reason to couple the two (even though DNS challenge is mandatory for wildcards)

**Comment by Skeletor11** [comment]
Just curious if the support for wildcard certs has been completed or still being worked on

**Comment by ohadschn** [comment]
@Skeletor11 I'm looking at it. Love the alias BTW

**Comment by ohadschn** [comment]
I'm currently blocked: https://github.com/sjkp/letsencrypt-siteextension/issues/183#issuecomment-486741035

**Comment by ohadschn** [comment]
Looks like there's a new NuGet version that unblocks this: https://www.nuget.org/packages/LetsEncrypt.Azure.Core.V2/

**Comment by ohadschn** [comment]
So unfortunately it turns our that while that version unblocks the ACME V2 part, it removes the DNS challenge part which is also needed for wildcard certs.

**Comment by ohadschn** [comment]
Implemented in the newest release: https://github.com/ohadschn/letsencrypt-webapp-renewer/releases/tag/1.0.5
