### ISSUE TITLE
Doesn't work together with the local cache feature

### ISSUE THREAD

**Issue by flagbug** [ohadschn/letsencrypt-webapp-renewer#45]
Azure App Service has a feature called "Local Cache" that cached the file system of the web app on each instance, see https://docs.microsoft.com/en-us/azure/app-service/app-service-local-cache-overview

I think the problem here is the following:

- On instance startup, the file system is copied to the instance
- When the renewer renews the certificate, it stores a verification file in the web apps source storage
- Since the filesystem of each instance is cached and not shared, the instances don't see the file until the next restart
- The verification request from Letsencrypt to `.well-known/acme-challenge/` fails, because to verification file can't be found in the instance local cache

Any ideas how to work around this? Maybe the verification file could be saved to an Azure Blob Storage instance that is then server from the host instance?

**Comment by flagbug** [comment]
Whoops, just saw that this is already stated in the README and probably belongs to the  https://github.com/sjkp/letsencrypt-siteextension repo

**Comment by ohadschn** [comment]
Indeed :)
Closing this for now.
