### ISSUE TITLE
Only send single summary email for provioning 

### ISSUE THREAD

**Issue by jonocairns** [ohadschn/letsencrypt-webapp-renewer#46]
Currently you get one email per app service certificate renewal. It'd be nice if this was just a single email with something along the lines of 

app-service-name: success
app-service-name: renewal not required
...etc

Cheers!

**Comment by ohadschn** [comment]
Hi @jonocairns,

I actually prefer it the way it is for two reasons:
1. If anything goes wrong in the middle of the WebJob you get the e-mails for the certs that were renewed (if I wait until everything completes, no e-mail will be sent even though some were renewed).
2. It's easier to quickly see exactly what got renewed, both for human eyes and possibly for automation as well (e.g. send SMS according to some text in the subject). 

If you feel you're getting too many emails you could just create a rule/filter that moves them to a folder/label. If you still prefer a single mail you could use a service like [Zapier](https://zapier.com/apps/windows-azure-web-sites/integrations), but that will only tell you about success/failure.
