### ISSUE TITLE
Implement renewer as Azure Function to save money

### ISSUE THREAD

**Issue by Ciantic** [ohadschn/letsencrypt-webapp-renewer#49]
If this only needs to be called e.g. once in 90 days it's wasteful to do this as an app service.

Instead figuring out how to do this same thing as a Azure Function would be beneficial.

**Comment by ohadschn** [comment]
I don't think it's that wasteful seeing as you already have a web app running, so you could just [use the same web app for the renewal site:](http://www.hanselman.com/blog/PennyPinchingInTheCloudWhenDoAzureWebsitesMakeSense.aspx). I suppose you do have to use "always on" which may take up some memory but I don't think it's significant. 

At any rate, for an equivalent Azure Function look here: http://wp.sjkp.dk/lets-encrypt-on-azure-web-apps-using-a-function-app-for-automated-renewal/.
