### ISSUE TITLE
Web Root Path 

### ISSUE THREAD

**Issue by Richy1989** [ohadschn/letsencrypt-webapp-renewer#55]
My Azure Web App (Running a Blazer Application) was always redirecting every request to a subfolder of `wwwroot`. So that the ACME Challange (`.well-known` directory) could not be found on the server. 

After checking the code of `LetsEncrypt.SiteExtension.Core` I found the configuration parameter: 
`letsencrypt:WebRootPath`. With this parameter the path of the `.well-known` directory could be changed.  

I suggest adding that parameter into the PowerShell script.

**Comment by ohadschn** [comment]
OK, I see it too: https://github.com/sjkp/letsencrypt-siteextension/blob/f2e8f392cd7706d3f71bc5d1fcbde1e69d120e91/LetsEncrypt.SiteExtension.Core/Services/KuduFileSystemAuthorizationChallengeProvider.cs#L71

So just to clarify, you were able to use this setting successfully with the `letsencrypt-webapp-renewer` webjob?

**Comment by jaykay-design** [comment]
The latest version of the LE extension now allows passing the webroot path programmatically.
