### ISSUE TITLE
End-of-Life for All TLS-SNI-01 Validation Support

### ISSUE THREAD

**Issue by Kalt** [ohadschn/letsencrypt-webapp-renewer#63]
Hello,

I have received an email about end of TLS-SNI-01 and I am not sure, if this will affect functionality of this awesome project? I am using Azure WebJob Renewal tool from this repo for multiple projects and it works flawlessly - at least for now.

Thank you very much for your work!

> Hello,
> *Action is required to prevent your Let's Encrypt certificate renewals from breaking.*
> Your Let’s Encrypt client used ACME TLS-SNI-01 domain validation to issue a certificate in the past 60 days.
> TLS-SNI-01 validation is reaching end-of-life and will stop working on *February 13th, 2019.*
> You need to update your ACME client to use an alternative validation method (HTTP-01, DNS-01 or TLS-ALPN-01) before this date or your certificate renewals will break and existing certificates will start to expire.
> 
> If you need help updating your ACME client, please open a new topic in the Help category of the Let's Encrypt community forum: 
> https://community.letsencrypt.org/c/help
> Please answer all of the questions in the topic template so we can help you.
> 
> For more information about the TLS-SNI-01 end-of-life please see our API announcement:
> https://community.letsencrypt.org/t/february-13-2019-end-of-life-for-all-tls-sni-01-validation-support/74209
> Thank you,
> Let's Encrypt Staff

**Comment by ohadschn** [comment]
Strange that you got this mail, the webjob only ever uses HTTP validation so `TLS-ALPN-01` deprecation is irrelevant: https://github.com/sjkp/letsencrypt-siteextension/issues/189.
