### ISSUE TITLE
Another Option for Scheduling

### ISSUE THREAD

**Issue by dkershner6** [ohadschn/letsencrypt-webapp-renewer#64]
Hi there!

Aside from some windows file/directory length issues when publishing locally, everything went very smoothly with the use of your app, and I like not relying on web app extensions as much as possible.

Since I am mostly serverless, I do not have a basic or greater app service, and therefore looked to your Scheduler-based recommendation.  Scheduler is now also not free ($14/mo at time of writing).

So, I came up with an Azure Functions based approach (Free, or the nearest to Free imaginable): https://github.com/eformedpartners/AzureWebJobScheduler/

What would be required to use your app with it:
* Delete or stop copying settings.job to deploy.
* Fill out all of the characteristics of the web app they installed this app on into the Functions App.
* Set the TimerCRONInterval appsetting with desired CRON (can copy yours if desired).

And that's it!

Just thought I would post it here for others.  Up to you if you replace scheduler in the readme with it instead.

**Comment by ohadschn** [comment]
Sounds great, would you mind submitting a PR for the README with this information?
