### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by Jogai** [ohadschn/letsencrypt-webapp-renewer#65]
Are you planning on building a new release? The site extension has seen improvements since the latest build as did your procect.

And a different question: does this restart the webapp during/after certification installation?

**Comment by ohadschn** [comment]
Yes I'm planning to build a new release (hopefully in the following week or so). 
It was only recently that an updated [NuGet](https://www.nuget.org/packages/letsencrypt.azure.core) for the extension's logic was released and I wasn't around GH at the time, only catching up now...

Regarding your second question, I don't think a restart takes place, but you could try asking here: https://github.com/sjkp/letsencrypt-siteextension

**Comment by Jogai** [comment]
Oh sorry, now I see it too. I was more looking at the commits. I was building from source, and noticed the nuget update. I tried it, and I can confirm that 0.8.5 => 0.9.0 is really a breaking change 😃

**Comment by ohadschn** [comment]
Can't say I'm surprised 😅

**Comment by Jogai** [comment]
Thanks for the update. It works without changing my config 😃
