### ISSUE TITLE
option to use letsencrypt staging environment

### ISSUE THREAD

**Issue by MingweiSamuel** [ohadschn/letsencrypt-webapp-renewer#66]
When the webjob is misconfigured it restarts over and over again and very quickly blows through the 5 cert/week limit, so it would be great if there was an option to use the letsencrypt staging environment which has much higher limits

**Comment by ohadschn** [comment]
This is supported - you can set [letsencrypt:webAppName-acmeBaseUri](https://github.com/ohadschn/letsencrypt-webapp-renewer#configuration) to the [staging] (https://letsencrypt.org/docs/staging-environment/) base URI `https://acme-staging.api.letsencrypt.org/`.
More info: https://letsencrypt.org/docs/acme-protocol-updates/

**Comment by bares43** [comment]
For ACMEv2 it's `https://acme-staging-v02.api.letsencrypt.org/directory` (it's not working without `directory` at the end).
