### ISSUE TITLE
Fails to validate cert when site is deployed using "run from package" option

### ISSUE THREAD

**Issue by rbanks54** [ohadschn/letsencrypt-webapp-renewer#80]
I ran into an issue where I deployed a new azure web site using the "run from package" approach (https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package).

Because this approach deploys a site in read-only mode, the `/.well-known` folder needed for the LetsEncrypt validation can't be created on the file system, causing the certificate renewal process to fail.

There's no message indicating this is the specific problem, beyond a 404 when trying to hit the URL. It should be detectable via the presence of a `WEBSITE_RUN_FROM_PACKAGE` setting.

It also might be worth adding a note to the readme to indicate this is a constraint and that sites should be zip or web deployed instead.

Do you want contributions for this?

**Comment by ohadschn** [comment]
Sure, would be happy for a PR as I am unfamiliar with this deployment approach...

**Comment by rbanks54** [comment]
Haha. Never mind. I'm giving myself a 🤦‍♂ 

I started looking through the code and then realised the fix would require a change in @sjkp's code. So I looked there and saw a discussion about it at https://github.com/sjkp/letsencrypt-siteextension/issues/239, and that it was resolved a while ago.

And then I went back and re-read the readme here and I saw this:

`letsencrypt:webAppName-webRootPath` (optional, defaults to `%HOME%\site\wwwroot` or **_in case of running from package_**: `%HOME%\site\letsencrypt`)

Let's pretend this issue was never reported 🐑 😄

**Comment by ohadschn** [comment]
LOL, if I had a penny for every time it happened to me...
Good thing it's documented here now, thanks :)

**Comment by karlok05** [comment]
I add %HOME%\site\letsencrypt to letsencrypt:webAppName-webRootPath but fails everytime in log writes:Could not find file 'D:\\home\\site\\wwwroot\\.well-known\\acme-challenge'.'.","ExceptionMessage"
