### ISSUE TITLE
ACMEv2

### ISSUE THREAD

**Issue by leyshon** [ohadschn/letsencrypt-webapp-renewer#90]
Is there any plan to update this to support ACMEv2? The letsencrypt.azure.core package has itself recently been updated to support ACMEv2. The v1 API is due to be retired at the start of November.

**Comment by ohadschn** [comment]
Thanks, I know, and I will try and release a new version before the deadline.

**Comment by ohadschn** [comment]
I have V2 working, hope to publish a release soon

**Comment by ohadschn** [comment]
Released https://github.com/ohadschn/letsencrypt-webapp-renewer/releases/tag/1.0.4
