### ISSUE TITLE
Support for Linux based Azure Web Apps

### ISSUE THREAD

**Issue by serkanozkul** [ohadschn/letsencrypt-webapp-renewer#95]
Are there any plans to support Linux based Azure Web Apps?

**Comment by ohadschn** [comment]
Just to clarify:
1. WebJobs [are not supported on linux](https://docs.microsoft.com/en-us/azure/app-service/webjobs-create) and apparently [never will be](https://feedback.azure.com/forums/169385-web-apps/suggestions/32437156--linux-to-support-webjob-feature-on-webapp-for-co)
1. AFAIK `letsencrypt-webapp-renewer`, when run from a Windows Azure Web App, will happily renew linux-based Azure Web Apps (I don't see why it would care).
