### ISSUE TITLE
Support ACMEv2?

### ISSUE THREAD

**Issue by optiks** [ohadschn/letsencrypt-webapp-renewer#96]
I received the following email from Let's Encrypt today:

> According to our records, the software client you're using to get Let's
Encrypt TLS/SSL certificates issued or renewed at least one HTTPS certificate
in the past two weeks using the **ACMEv1 protocol**. 

> Beginning June 1, 2020, we will stop allowing new domains to validate using
the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before
then, or certificate issuance will fail. For most people, simply upgrading to
the latest version of your existing client will suffice.

Looking at the source, it [_appears_ to reference ACMEv2](https://github.com/ohadschn/letsencrypt-webapp-renewer/blob/92cb50b2ff39998d788a4cbc638bde712a0230d4/src/OhadSoft.AzureLetsEncrypt.Renewal/Management/RenewalManager.cs#L20), in which case I'm confused about why I got this email?

Can you please clarify if the current client is using ACMEv2, and if it's not, whether there's a plan to upgrade it to this version or not?

**Comment by shah-gaurav** [comment]
As per issue #90 it seems like Acme V2 support has already been released. It should just be a matter of updating to the latest version. I am going to try it out myself.

**Comment by ohadschn** [comment]
Indeed, the latest version uses ACME V2: https://github.com/ohadschn/letsencrypt-webapp-renewer/releases

**Comment by mos-ie** [comment]
Hi there, I use this in a web job - any instructions on how to upgrade without impacting websites that are listed in letsencrypt:webApps?

**Comment by ohadschn** [comment]
@mos-ie not sure what you mean, upgrading simply means removing the previous webjob and placing the new webjob in its stead. They will use the same configuration, including `letsencrypt:webApps`. If you need further clarification please open a new issue with more details.
