### ISSUE TITLE
letsencrypt:webApps value being cached?

### ISSUE THREAD

**Issue by paulbrown79** [ohadschn/letsencrypt-webapp-renewer#98]
Hello

When I update value for "letsencrypt:webApps" and save the configuration I wait for the Azure portal to confirm the save.

I hard refresh the page and the value of "letsencrypt:webApps" is as expected.

If I now run the WebJob for the renewal, the renewal run but with the previously saved value in "letsencrypt:webApps" and therefore renews the wrong domains.

I need to wait about 15 minutes before the WebJob picks up the new value saved to "letsencrypt:webApps".

Anyone else had any similar problems?

Thanks

Paul

**Comment by ohadschn** [comment]
The WebJob code is not doing any caching, all settings are read directly from `System.Configuration.ConfigurationManager` (this is the [standard method](https://stackoverflow.com/a/45156928/67824)): https://github.com/ohadschn/letsencrypt-webapp-renewer/blob/5886398b5f5b205bf2019dd41141875d1bd1ed83/src/OhadSoft.AzureLetsEncrypt.Renewal.WebJob/Program.cs#L51

Your question is better suited for Azure support: https://azure.microsoft.com/en-us/support/community/
